name: Pipeline de Pruebas Automatizadas

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pruebas:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar pruebas automatizadas
      run: npm test

    - name: Generar reporte de cobertura
      run: npm run coverage

    - name: Subir reporte
      uses: actions/upload-artifact@v4
      with:
        name: reporte-cobertura
        path: coverage/